# This rule is not used by the project hltest-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over example.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hltest-operator
    app.kubernetes.io/managed-by: kustomize
  name: hltest-admin-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - hltests
  verbs:
  - '*'
- apiGroups:
  - example.example.com
  resources:
  - hltests/status
  verbs:
  - get
